name: eda
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - hydra-core=1.3.2
  - matplotlib=3.7.2
  - pandas=1.5.3
  - scikit-learn=1.2.2
  - jupyterlab=3.6.8
  - pip
  - pip:
      - mlflow==2.14.1
      - wandb==0.21.3
      - ydata-profiling==4.6.4
      - ipywidgets==7.7.2
