name: components
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pyyaml
  - hydra-core=1.3.2
  - pandas=1.5.3          
  - pip                   
  - pip:
      - mlflow==2.14.1
      - wandb==0.21.3
