name: basic_cleaning
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - hydra-core=1.3.2
  - matplotlib=3.5.3
  - pandas=1.5.3 
  - scikit-learn=1.3.2
  - pip
  - pip:
      - mlflow==2.14.1
      - wandb==0.21.3
